"""End-to-end run: build the database, train, tune, and produce the figures.

Reproduces every number and every figure in ``artifacts/``. Takes roughly half an
hour on four cores.

The corpus is SYNTHETIC — generated by the physically-based water balance in
``smml.physics.simulator``, not measured in the field. The environment this was
built in has no network access to any soil moisture data host, so no real
observation could be harvested. What this run demonstrates is that the pipeline
works end to end and that its diagnostics behave correctly; it says nothing about
accuracy on real soils. Every figure carries that notice.
"""

from __future__ import annotations

import json
import logging
import time
from pathlib import Path

import numpy as np
import pandas as pd

from smml.cli._pipeline import CLAY_CORRECTED_TARGET
from smml.db.store import Store
from smml.eval.metrics import compute_metrics, metrics_by_group, skill_decomposition
from smml.eval.runner import compare_models, run_cv
from smml.eval.splits import get_splitter
from smml.eval.targets import beats_the_sensor, evaluate_targets
from smml.features.build import build_features
from smml.models.baselines import (
    BucketBaseline,
    DepthClimatologyBaseline,
    FieldCapacityBaseline,
    GlobalMeanBaseline,
)
from smml.models.gbdt import LightGBMModel, XGBoostModel
from smml.physics.dielectric import correct_for_clay
from smml.physics.simulator import generate_corpus
from smml.qc.checks import qc_summary, run_qc
from smml.util.ids import observation_key, sensor_id
from smml.viz import figures

logging.basicConfig(level=logging.INFO, format="%(asctime)s  %(message)s",
                    datefmt="%H:%M:%S")
log = logging.getLogger("pipeline")

ROOT = Path(__file__).resolve().parent.parent
ARTIFACTS = ROOT / "artifacts"
FIGURES = ARTIFACTS / "figures"
RESULTS = ARTIFACTS / "results"
DATABASE = ARTIFACTS / "database"

N_SITES = 100
YEARS = 5
SEED = 20240915
FOLDS = 5
TUNING_TRIALS = 30


def stage(name: str):
    log.info("=" * 68)
    log.info(name)
    log.info("=" * 68)


def main() -> None:
    for directory in (FIGURES, RESULTS, DATABASE):
        directory.mkdir(parents=True, exist_ok=True)
    started = time.time()
    summary: dict = {"config": {"n_sites": N_SITES, "years": YEARS, "seed": SEED,
                                "folds": FOLDS, "tuning_trials": TUNING_TRIALS}}

    # ---------------------------------------------------------------- corpus
    stage(f"1. Generating a synthetic corpus: {N_SITES} sites x {YEARS} years")
    observations, sites = generate_corpus(n_sites=N_SITES, years=YEARS, seed=SEED)
    observations["date"] = pd.to_datetime(observations["date"])
    log.info("%d observations at %d sites, %d depths",
             len(observations), sites.shape[0], observations.depth_top_cm.nunique())

    # Apply the sensor-physics correction, to its own column.
    merged = observations.merge(sites[["site_id", "clay_pct"]], on="site_id", how="left")
    observations[CLAY_CORRECTED_TARGET] = pd.Series(
        correct_for_clay(merged["theta_obs_m3m3"].to_numpy(float),
                         merged["clay_pct"].to_numpy(float),
                         merged["layer_porosity_m3m3"].to_numpy(float)),
        index=merged.index,
    ).fillna(merged["theta_obs_m3m3"])

    # ------------------------------------------------------------- database
    stage("2. Writing the harmonized database")
    store = Store(DATABASE)
    facts = observations.copy()
    facts["time_utc"] = pd.to_datetime(facts["date"], utc=True)
    facts["sensor_id"] = [
        sensor_id(s, "soil_moisture", t, b)
        for s, t, b in zip(facts.site_id, facts.depth_top_cm, facts.depth_bottom_cm,
                           strict=True)
    ]
    observation_rows = pd.DataFrame({
        "observation_key": [observation_key(s, str(t))
                            for s, t in zip(facts.sensor_id, facts.time_utc, strict=True)],
        "site_id": facts.site_id, "sensor_id": facts.sensor_id,
        "source_id": "synthetic_simulator", "time_utc": facts.time_utc,
        "depth_top_cm": facts.depth_top_cm.astype("float32"),
        "depth_bottom_cm": facts.depth_bottom_cm.astype("float32"),
        "theta_m3m3": facts.theta_obs_m3m3.astype("float32"),
        "theta_clay_corrected_m3m3": facts[CLAY_CORRECTED_TARGET].astype("float32"),
        "saturation": facts.saturation.astype("float32"),
        "method": "fdr_capacitance", "quality_flag": "G",
        "uncertainty_m3m3": np.float32(0.035),
        "year": facts.time_utc.dt.year.astype("int16"),
        "network": "SYNTHETIC",
    })
    written = store.write("observations", observation_rows)

    site_rows = sites.rename(columns={
        "om_pct": "om_pct", "texture_class": "texture_class",
        "mean_annual_precip_mm": "mean_annual_precip_mm",
    }).copy()
    site_rows["source_id"] = "synthetic_simulator"
    site_rows["network"] = "SYNTHETIC"
    site_rows["irrigation_status"] = np.where(site_rows["is_irrigated"], "irrigated",
                                              "rainfed")
    site_rows["mean_annual_precip_mm"] = site_rows["annual_precip_mm"]
    site_rows["climate_zone"] = site_rows["climate"]
    keep = [c for c in site_rows.columns
            if c in {f.name for f in store.spec("sites").schema}]
    store.write("sites", site_rows[keep])

    weather_rows = observations.drop_duplicates(["site_id", "date"])[
        ["site_id", "date", "precip_mm", "tmax_c", "tmin_c", "tmean_c",
         "rh_mean_pct", "wind_2m_ms", "srad_mj_m2", "et0_mm"]
    ].copy()
    weather_rows["source_id"] = "synthetic_simulator"
    weather_rows["et0_method"] = "fao56_penman_monteith"
    weather_rows["year"] = pd.to_datetime(weather_rows["date"]).dt.year.astype("int16")
    store.write("weather", weather_rows)

    irrigation_rows = observations[observations.irrigation_mm > 0].drop_duplicates(
        ["site_id", "date"])[["site_id", "date", "irrigation_mm"]].copy()
    irrigation_rows = irrigation_rows.rename(columns={"irrigation_mm": "amount_mm"})
    irrigation_rows["evidence"] = "reported"
    irrigation_rows["confidence"] = 1.0
    irrigation_rows["source_id"] = "synthetic_simulator"
    irrigation_rows["year"] = pd.to_datetime(irrigation_rows["date"]).dt.year.astype("int16")
    store.write("irrigation", irrigation_rows)

    # One portable file alongside the partitioned store: the Parquet layout is
    # right for a harvest and wrong for handing to a colleague.
    store.export_duckdb(DATABASE / "soil_moisture.duckdb")
    store.export_csv(DATABASE / "csv", max_rows=200_000)

    db_summary = store.summary()
    log.info("\n%s", db_summary.to_string(index=False))
    db_summary.to_csv(RESULTS / "database_summary.csv", index=False)
    summary["database"] = {
        "observations": int(written),
        "total_mb": float(db_summary["mb"].sum()),
        "path": str(DATABASE),
    }

    # ------------------------------------------------------------------- qc
    stage("3. Quality control")
    qc_input = observations[observations.depth_mid_cm <= 30].rename(
        columns={"theta_obs_m3m3": "theta_m3m3"}).copy()
    qc_input["time_utc"] = qc_input["date"]
    qc_input["method"] = "fdr_capacitance"
    qc_input = qc_input.merge(
        sites[["site_id", "clay_pct", "porosity_m3m3", "ece_ds_m", "sensor_frequency_mhz"]],
        on="site_id").rename(columns={"sensor_frequency_mhz": "instrument_frequency_mhz"})
    qc_result = run_qc(qc_input, theta_col="theta_m3m3", date_col="time_utc")
    qc_table = qc_summary(qc_result)
    log.info("\n%s", qc_table.to_string(index=False))
    qc_table.to_csv(RESULTS / "qc_summary.csv", index=False)

    # -------------------------------------------------------------- features
    stage("4. Building features")
    frame, feature_cols, _ = build_features(observations, sites, target="theta_obs_m3m3")
    frame["date"] = pd.to_datetime(frame["date"])
    extra = observations[["site_id", "date", "depth_top_cm", CLAY_CORRECTED_TARGET]]
    frame = frame.merge(extra, on=["site_id", "date", "depth_top_cm"], how="left")
    cutoff = frame["date"].min() + pd.Timedelta(days=365)
    frame = frame[frame["date"] >= cutoff].reset_index(drop=True)
    log.info("%d rows, %d features after dropping the warm-up year",
             len(frame), len(feature_cols))
    summary["features"] = {"rows": int(len(frame)), "n_features": len(feature_cols)}

    splitter = get_splitter("leave_site_out", n_folds=FOLDS)
    truth = "theta_true_m3m3"

    # ---------------------------------------------------- model comparison
    stage("5. Leave-site-out cross-validation")
    factories = {
        "global mean": GlobalMeanBaseline,
        "depth climatology": DepthClimatologyBaseline,
        "field capacity (pedotransfer)": FieldCapacityBaseline,
        "water-balance bucket": BucketBaseline,
        "XGBoost": lambda: XGBoostModel(num_boost_round=700),
        "LightGBM": lambda: LightGBMModel(
            num_boost_round=900, params={"learning_rate": 0.05, "num_leaves": 127}),
    }
    table, results = compare_models(
        frame, feature_cols, CLAY_CORRECTED_TARGET, factories, splitter,
        split_name="leave_site_out", truth_col=truth,
        inner_validation_fraction=0.15, verbose=False,
    )
    columns = ["model", "rmse", "ubrmse", "bias", "r", "r2", "kge",
               "r_between", "r_within", "fit_seconds"]
    comparison = table[[c for c in columns if c in table.columns]]
    log.info("\n%s", comparison.round(4).to_string(index=False))
    comparison.to_csv(RESULTS / "model_comparison.csv", index=False)
    summary["model_comparison"] = comparison.round(5).to_dict("records")

    best_name = comparison.iloc[0]["model"]
    best = results[best_name]
    oof = best.oof[best.oof.fold >= 0].copy()

    # ------------------------------------------- raw target, for the contrast
    stage("6. The same model fitted to the raw sensor reading, for contrast")
    raw_result = run_cv(
        frame, feature_cols, "theta_obs_m3m3",
        lambda: LightGBMModel(num_boost_round=900,
                              params={"learning_rate": 0.05, "num_leaves": 127}),
        splitter, split_name="leave_site_out", truth_col=truth,
        inner_validation_fraction=0.15, verbose=False,
    )
    raw_oof = raw_result.oof[raw_result.oof.fold >= 0].copy()
    contrast = pd.DataFrame([
        {"trained_on": "raw sensor reading", **raw_result.overall, **raw_result.skill},
        {"trained_on": "clay-corrected reading", **best.overall, **best.skill},
    ])[["trained_on", "rmse", "ubrmse", "bias", "r", "r_between", "r_within"]]
    log.info("\n%s", contrast.round(4).to_string(index=False))
    contrast.to_csv(RESULTS / "clay_correction_contrast.csv", index=False)
    summary["clay_correction"] = contrast.round(5).to_dict("records")

    # --------------------------------------------------------------- tuning
    stage(f"7. Hyperparameter search, {TUNING_TRIALS} trials, site-disjoint inner folds")
    from smml.tune.search import TuningConfig, save_best_params, tune

    config = TuningConfig(n_trials=TUNING_TRIALS, n_inner_folds=3, metric="rmse",
                          study_name="full_run_lightgbm",
                          storage=f"sqlite:///{ARTIFACTS / 'optuna_full_run.db'}",
                          search_sample_fraction=0.35, n_startup_trials=8)
    tuning = tune(frame, feature_cols, CLAY_CORRECTED_TARGET,
                  lambda params: LightGBMModel(params=params, num_boost_round=600),
                  "lightgbm", config, truth_col=truth)
    log.info("best rmse %.5f with %s", tuning.best_value, tuning.best_params)
    save_best_params(tuning, RESULTS / "best_hyperparameters.yaml")
    if tuning.param_importance is not None:
        tuning.param_importance.to_csv(RESULTS / "hyperparameter_importance.csv",
                                       index=False)
    summary["tuning"] = {"best_rmse": float(tuning.best_value),
                         "n_trials": int(len(tuning.trials)),
                         "best_params": tuning.best_params}

    stage("8. Refitting with the tuned configuration")
    tuned = run_cv(
        frame, feature_cols, CLAY_CORRECTED_TARGET,
        lambda: LightGBMModel(params=dict(tuning.best_params), num_boost_round=1200),
        splitter, split_name="leave_site_out", truth_col=truth,
        inner_validation_fraction=0.15, verbose=False,
    )
    log.info("tuned: %s", tuned)
    if tuned.overall["rmse"] < best.overall["rmse"]:
        log.info("tuned model improves on the default; using it for the figures")
        best, oof = tuned, tuned.oof[tuned.oof.fold >= 0].copy()
    else:
        log.info("tuning did not improve on the default; keeping the default")
    summary["final"] = {**{k: float(v) for k, v in best.overall.items()},
                        **{k: float(v) for k, v in best.skill.items()
                           if isinstance(v, (int, float))}}

    # ------------------------------------------------------------- targets
    stage("9. Scoring against the success criteria")
    enriched = oof.merge(
        sites[["site_id", "clay_pct", "ece_ds_m", "texture_class"]].rename(
            columns={"clay_pct": "_clay", "ece_ds_m": "_ece", "texture_class": "_tex"}),
        on="site_id", how="left")
    for source, target in (("_clay", "clay_pct"), ("_ece", "ece_ds_m"),
                           ("_tex", "texture_class")):
        if target not in enriched.columns or enriched[target].isna().all():
            enriched[target] = enriched[source]
    enriched = enriched.drop(columns=["_clay", "_ece", "_tex"])

    for product in ("A", "B"):
        report = evaluate_targets(enriched, truth, "prediction", product=product,
                                  skill=best.skill)
        log.info("Product %s: %s", product, "PASS" if report.passed else "not met")
        log.info("\n%s", report.rows[["target", "value", "threshold", "passes"]]
                 .to_string(index=False))
        if report.leakage_warning:
            log.warning(report.leakage_warning)
        report.rows.to_csv(RESULTS / f"targets_product_{product}.csv", index=False)
        summary[f"product_{product}"] = {"passed": bool(report.passed),
                                         "rows": report.rows.to_dict("records")}
    sensor = beats_the_sensor(enriched, truth, "prediction")
    log.info("against a dielectric probe in difficult soils: %s", sensor)
    summary["beats_sensor"] = sensor

    # ------------------------------------------------------------- figures
    stage("10. Figures")
    notice = (f"Synthetic corpus: {N_SITES} sites x {YEARS} years from a "
              "physically-based water balance, not field measurements. "
              "Demonstrates the pipeline, not real-soil accuracy.")

    figures.measured_vs_predicted(
        enriched, truth, "prediction", out=FIGURES / "01_measured_vs_predicted.png",
        title="Measured against predicted soil water content, by depth",
        notice=notice)

    busiest = (enriched.groupby("site_id").size().sort_values(ascending=False)
               .head(3).index.tolist())
    figures.time_series(
        enriched[enriched.site_id.isin(busiest)], truth, "prediction",
        sites=busiest, depths=[2.5, 22.5, 80.0],
        out=FIGURES / "02_time_series.png",
        title="Measured and predicted through the season, held-out sites",
        notice=notice)

    _, depth_table = figures.performance_by_depth(
        enriched, truth, "prediction", out=FIGURES / "03_performance_by_depth.png",
        notice=notice)
    depth_table.to_csv(RESULTS / "performance_by_depth.csv", index=False)

    figures.error_by_stratum(
        enriched, truth, "prediction", out=FIGURES / "04_error_by_stratum.png",
        notice=notice)

    raw_enriched = raw_oof.merge(sites[["site_id", "clay_pct"]], on="site_id",
                                 how="left", suffixes=("", "_site"))
    if "clay_pct" not in raw_enriched or raw_enriched["clay_pct"].isna().all():
        raw_enriched["clay_pct"] = raw_enriched["clay_pct_site"]
    figures.clay_correction_effect(
        raw_enriched, enriched, truth, "prediction",
        out=FIGURES / "05_clay_correction_effect.png", notice=notice)

    _, decomposition = figures.skill_decomposition_figure(
        enriched, truth, "prediction", out=FIGURES / "06_skill_decomposition.png",
        notice=notice)
    summary["skill_decomposition"] = {k: float(v) for k, v in decomposition.items()}

    if best.importance is not None:
        best.importance.head(40).to_csv(RESULTS / "feature_importance.csv", index=False)

    by_texture = metrics_by_group(enriched, truth, "prediction", "texture_class")
    by_texture.to_csv(RESULTS / "performance_by_texture.csv", index=False)
    oof_out = enriched[["site_id", "date", "depth_top_cm", "depth_bottom_cm",
                        "depth_mid_cm", truth, "theta_obs_m3m3", "prediction",
                        "fold", "clay_pct", "ece_ds_m", "texture_class"]]
    oof_out.to_parquet(RESULTS / "out_of_fold_predictions.parquet", index=False)
    log.info("wrote %d out-of-fold predictions", len(oof_out))

    summary["elapsed_minutes"] = round((time.time() - started) / 60, 1)
    (RESULTS / "run_summary.json").write_text(json.dumps(summary, indent=2, default=str))
    stage(f"Done in {summary['elapsed_minutes']} minutes. Artifacts in {ARTIFACTS}")


if __name__ == "__main__":
    main()
